#ifndef TESTVIMINPUTHANDLER_H
#define TESTVIMINPUTHANDLER_H

#include <QObject>

class TestVimInputHandler : public QObject
{
    Q_OBJECT

private slots:
    void searchEditorDestruction();
    void searchFoldAndJumpRestoration();
    void searchFocusCancellation();
    void searchNavigation_data();
    void searchNavigation();
    void searchPreviewCancellation();
    void searchHistoryAndInvalidPatterns();
    void searchHighlightLifecycle();
    void searchVisualAndTemporaryNormal();
    void searchMacrosAndMappings();
    void nativeFolding();
    void insertIndentation();
    void visualRegisterPaste_data();
    void visualRegisterPaste();
    void visualPasteHistory_data();
    void visualPasteHistory();
    void visualPasteReadOnly();
    void visualPasteRepeatUndo();
    void visualBlockPaste_data();
    void visualBlockPaste();
    void visualBlockPasteHistory();
    void visualBlockPasteRepeatReadOnly();
    void gMotionNavigation();
    void gAndFindOperators_data();
    void gAndFindOperators();
    void visualFindMotions();
    void findRepeatFailureAndMappings();
    void horizontalPreferredColumn();
    void changeHistory();
    void registerHistories_data();
    void registerHistories();
    void numberedRegisterRotation();
    void registerPasteShapes();
    void blockRegisterHistory();
    void insertRegisterClipboardAndCancel();
    void insertRegisterCountRepeatUndo();
    void readOnlyRegisterOperations();
    void lineStartMotions();
    void backwardEndOperators();
    void insertControlDeletion();
    void insertCompletionCycles();
    void insertCompletionUnicodeAndSafety();
    void insertCompletionResets();
    void insertCompletionDotRepeat();
    void insertCompletionRepeatEdges();
    void insertCompletionMacroIsDynamic();
    void insertBackspaceAnchors();
    void replaceBackspacing();
    void countedInsert();
    void numericAndSqlMappings();
    void blockEditing();
    void configMappings();
    void findRepeatAndMarks();
    void builtinCommands_data();
    void builtinCommands();
    void repeatAndMacro();
    void substitution();
    void substitutionConfirmation_data();
    void substitutionConfirmation();
    void substitutionConfirmationUnicodeAndZeroLength();
    void substitutionConfirmationLifecycle();
    void substitutionConfirmationCommandUi();
    void exLineCommands_data();
    void exLineCommands();
    void exRangesAndMarks();
    void exRejectsInvalidCommands();
    void exVisualRange();
    void surround_data();
    void surround();
    void paragraphAndSentenceObjects_data();
    void paragraphAndSentenceObjects();
    void paragraphAndSentenceSelections();
    void tagObjects_data();
    void tagObjects();
    void tagObjectSelectionsAndRegisters();
    void textObjects_data();
    void textObjects();
    void enhancedMotions();
    void mappingPrefixAndEscape();
    void insertAndEscape();
    void insertOneNormalCommand_data();
    void insertOneNormalCommand();
    void insertOneNormalPending();
    void insertOneNormalRepeatAndMacros();
    void insertOneNormalUndoAndReadOnly();
    void insertOneNormalEx();
    void insertOneNormalSubstitutionConfirmation_data();
    void insertOneNormalSubstitutionConfirmation();
    void insertOneNormalSubstitutionExternalCancellation();
    void insertCtrlWDeletesPreviousWord();
    void normalMotionsAndDelete();
    void wordEndMotionIncludesPunctuationAcrossLines();
    void customInsertMappings();
    void customNormalMappings();
    void countedLineDelete();
    void visualDelete();
    void yankAndPasteLine();
    void undoAndRedo();
    void operatorMotion();
    void matchingBraceOperator();
    void appendAndOpenLines();
    void visualLineDelete();
    void windowsLineEndings();
    void externalClipboardPaste();
    void disabledLeavesEditorUnchanged();
};

#endif
